### ISSUE TITLE
Alias this for classes is deprecated in DMD 2.103

### ISSUE THREAD

**Issue by JecksteRu** [godot-dlang/godot-dlang#104]
> Using alias this for classes has not been clearly specified and the lookup rules in such circumstances are not defined. As a consequence, various failures or crashes may appear when alias this is used in conjunction with classes. Starting with this release, alias this for classes is being deprecated.

https://dlang.org/changelog/2.103.0.html

**Comment by al1-ce** [comment]
Closing in favour of #112
