### ISSUE TITLE
Todo: Update license dates

### ISSUE THREAD

**Issue by nxuv** [godot-dlang/godot-dlang#112]

**Comment by Superbelko** [comment]
don't bother with it, I've read an article saying that only the first date is relevant, so now more and more companies and projects drops old style multi-line copyrights in every header in favor of shorter one.

Can't give exact source but should be pretty easy to find discussions about that.

**Comment by al1-ce** [comment]
Gotta update it to this smaller format then to save pain later

**Comment by al1-ce** [comment]
Fixed by #120
