### ISSUE TITLE
Floating point arguments bug

### ISSUE THREAD

**Issue by Superbelko** [godot-dlang/godot-dlang#121]
### Issue

There is a bug related to `@Method` parameters, when user declares a method with floating type doesn't matching godot's `real_t` size (`double` by default), this conversion produces incorrect result.

https://github.com/godot-dlang/godot-dlang/blob/40d849d8fc77f9bcbf0b6276b840c3a44fabb880/src/godot/api/wrap.d#L320-L322

Example:
```d
@Method _process(float delta) {
 // delta here contains garbage
}

@Method update(double delta) {
 // here delta is correct
}
```

### How to fix

Suggested fix is to cast to godot `real_t` pointer first and cast to target type, also double ptr was probably due to mistake or an older godot4 alpha quirks.

```d
return cast(A[ai]) *cast(real_t*) &va[ai]; 
```

**Comment by al1-ce** [comment]
From gd4 release notes in c# section:
> One of the most notable changes is the use of 64-bit types as scalar values. This means many APIs that used int or float now use long and double with the most noticeable being the _Process method. A Variant type is also now implemented in every API that takes variants where System.Object was used in the past. This brings some improvements such as avoiding boxing the values.

So it's pretty much easy to assume they want everyone to use it

Question is to cast or not to cast
If to cast then we arent really loosing anything, but there must be hardcoded assert before that check if delta is floating point (which if i remember correctly should be in std.traits module)

**Comment by Superbelko** [comment]
It is not about to cast or not to cast, it is low level C ABI interface and how they design parameter passing in engine code/GDExtension interface.

In our case it is not a variant despite being variant[]* being used, it is pointer to caller arguments location.
Even though in this case we might just abuse private implementation details that we shouldn't rely on - it could be that such construct on our side works only because Godot Variant implemented as union and we are lucky to have pointer landed upon it, otherwise we would have garbage.

As this was done in early alpha days I can't even tell the reasoning behind this design decision, back then there was no info at all, no docs, no examples, nowhere to look for a reference.

**Comment by Superbelko** [comment]
Closing issue as fixed.
