### ISSUE TITLE
Potentially outdated package in DUB registry

### ISSUE THREAD

**Issue by dd86k** [godot-dlang/godot-dlang#122]
I've been using godot-dlang v0.2.0 without any issue! (So far on Windows, making a debugger)

Though, the godot-dlang package in the DUB registry (https://code.dlang.org/packages/godot-dlang) is at v0.2.0 and doesn't seem up-to-date as noticing v0.3.0 being tagged here. I'm sure triggering a manual update over there will likely pull the newer version in.

Diff v0.2.0..v0.3.0 seems like it contains a bugfix or two, so could be worthwhile.

**Comment by al1-ce** [comment]
I have no idea why dub didn't pull new version automatically

Fixed, thanks for letting know

**Comment by Superbelko** [comment]
It does, but for a quite some time it happens very slowly, e.g. last time when v0.2 was released I had to search package on dub registry and navigate here and there few times, then I did dub fetch, and only after a week or so it was finally picked up new version. 
Annoying.
