### ISSUE TITLE
Godot 4.2 Dev 4

### ISSUE THREAD

**Issue by SpiceyWolf** [godot-dlang/godot-dlang#130]
This was in their snapshot article:
`
Initial work was merged to improve the developer experience with GDExtension on Windows, by copying DLLs to a temporary location before opening them ([GH-80188](https://github.com/godotengine/godot/pull/80188)). This makes it possible to overwrite the original DLL (e.g. by compiling a new version) without running into Windows file locking conflicts. This paves the way to implementing live reloading of GDExtension, for which a PR is currently open and ready for testing ([GH-80284](https://github.com/godotengine/godot/pull/80284)).
`
A while back there was mention of a hot-reload issue going on, this is probably relevant to it. Article link here: https://godotengine.org/article/dev-snapshot-godot-4-2-dev-4/

As the fourth from bottom bullet point just before 'Whats New'

**Comment by Superbelko** [comment]
Well, if there is no breaking API changes in extension manager it might work now.
I'll see if that hot reload works this weekend.

Unfortunately they've break 4.1 so our CI is now basically useless and I'm not very happy about making it even more optional, will probably switch to first 4.2 beta early next month, no time to mess with dev releases.

**Comment by SpiceyWolf** [comment]
What do you meen making it even more optional? Sorry, Ive been away from any development for a good while and def outta the loop what yall've had going on (mental health)

**Comment by Superbelko** [comment]
Nothing fancy, it seems godot 4.1.1 release has broken something, now we need to move some parts of autotester to optional tests (i.e. editor can't export when there is gdextension loaded, ugh...)

**Comment by Superbelko** [comment]
To my surprise it seems `godot-4.1` branch works with current 4.2 dev6, there is missing docs but it could be again a godot bug.

**Comment by SpiceyWolf** [comment]
They added a system of having backwards compatibility already... afaik if ur headers are on a old version it should just take it bugs and all

**Comment by Superbelko** [comment]
I have no idea what's wrong with 4.2 but it crashes a lot, randomly, heap corruption and all that stuff w.r.t to double freeing. 
Test project is horribly broken right now, while asteroids seems to work ok but there is no arrays or strings involved.

At first I was thought it was my retarded code but i can't pin it and this doesn't seem to be related to our broken ref counting.

**Comment by SpiceyWolf** [comment]
The beta 2 release notes mentioned this:
`Editor: Fix StringName leaks in GDExtension, core, and editor themes`

**Comment by Superbelko** [comment]
I've seen this when looking for possible issues before messing up even more with the code.
Indeed, after fixing most of the issues number of leaked StringName refs is now just 22 for test project, these leftovers are probably from String wrapper itself.

Unfortunately there is yet another bug related to String ownership so I can't just turn on the destructors yet...

**Comment by SpiceyWolf** [comment]
Im sure itll all be knocked out by the final release of 4.2 :)

**Comment by Superbelko** [comment]
@SpiceyWolf can you please test this new sweet 4.2 branch?  PR https://github.com/godot-dlang/godot-dlang/pull/143
Even just a basic "compiles, launches, closes without exploding" will do.
It should "mostly work" now, hopefully I'd never have to debug refcounting again.

I would definitely need some help testing it after dealing with all this mess as I haven't had a chance on trying latest changes on a real project due to time constraints...

**Comment by SpiceyWolf** [comment]
Yea lemme get everything setup again... been a minute since i did any non gdscript stuff lol

**Comment by SpiceyWolf** [comment]
`Running lib/generator -j extension_api.json -o
["/home/spiceywolf/Desktop/4_2_Dlang/src/godot-dlang/lib/generator"]
Outputting to default directory /home/spiceywolf/Desktop/4_2_Dlang/src/godot-dlang/classes...
object.Exception@../../../../.dub/packages/mir-algorithm/3.21.0/mir-algorithm/source/mir/parse.d(110): fromString failed to parse int
----------------
../../../../.dub/packages/mir-algorithm/3.21.0/mir-algorithm/source/mir/parse.d:139 pure @nogc @safe int mir.parse.fromString!(int).fromString!(char).fromString(scope const(char)[]) [0x5588bba70851]
../../../../.dub/packages/mir-core/1.6.0/mir-core/source/mir/conv.d:96 pure @nogc @safe int mir.conv.to!(int).to!(immutable(char)[]).to(immutable(char)[]) [0x5588bba707c7]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:2121 pure @nogc mir.serde.SerdeException asdf.serialization.deserializeValue!(int).deserializeValue(asdf.asdf.Asdf, ref int) [0x5588bba7079c]
../../../../.dub/packages/mir-algorithm/3.21.0/mir-algorithm/source/mir/serde.d:2325 pure @nogc mir.serde.SerdeException mir.serde.deserializeValueMemberImpl!(asdf.serialization.deserializeValue, asdf.serialization.deserializeScopedString).deserializeValueMemberImpl!("value", asdf.asdf.Asdf, godot.tools.generator.enums.EnumValues).deserializeValueMemberImpl(asdf.asdf.Asdf, scope ref godot.tools.generator.enums.EnumValues, scope ref mir.serde.SerdeFlags!(godot.tools.generator.enums.EnumValues).SerdeFlags) [0x5588bba7647e]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:2901 pure mir.serde.SerdeException asdf.serialization.deserializeValue!(godot.tools.generator.enums.EnumValues).deserializeValue(asdf.asdf.Asdf, ref godot.tools.generator.enums.EnumValues) [0x5588bba762bc]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:2306 pure mir.serde.SerdeException asdf.serialization.deserializeValue!(godot.tools.generator.enums.EnumValues[], godot.tools.generator.enums.EnumValues).deserializeValue(asdf.asdf.Asdf, ref godot.tools.generator.enums.EnumValues[]) [0x5588bba7614e]
../../../../.dub/packages/mir-algorithm/3.21.0/mir-algorithm/source/mir/serde.d:2325 pure mir.serde.SerdeException mir.serde.deserializeValueMemberImpl!(asdf.serialization.deserializeValue, asdf.serialization.deserializeScopedString).deserializeValueMemberImpl!("values", asdf.asdf.Asdf, godot.tools.generator.enums.GodotEnum).deserializeValueMemberImpl(asdf.asdf.Asdf, scope ref godot.tools.generator.enums.GodotEnum, scope ref mir.serde.SerdeFlags!(godot.tools.generator.enums.GodotEnum).SerdeFlags) [0x5588bba7604a]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:2901 pure mir.serde.SerdeException asdf.serialization.deserializeValue!(godot.tools.generator.enums.GodotEnum).deserializeValue(asdf.asdf.Asdf, ref godot.tools.generator.enums.GodotEnum) [0x5588bba75e54]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:2306 pure mir.serde.SerdeException asdf.serialization.deserializeValue!(godot.tools.generator.enums.GodotEnum[], godot.tools.generator.enums.GodotEnum).deserializeValue(asdf.asdf.Asdf, ref godot.tools.generator.enums.GodotEnum[]) [0x5588bba75cca]
../../../../.dub/packages/mir-algorithm/3.21.0/mir-algorithm/source/mir/serde.d:2325 pure mir.serde.SerdeException mir.serde.deserializeValueMemberImpl!(asdf.serialization.deserializeValue, asdf.serialization.deserializeScopedString).deserializeValueMemberImpl!("enums", asdf.asdf.Asdf, godot.tools.generator.classes.GodotClass).deserializeValueMemberImpl(asdf.asdf.Asdf, scope ref godot.tools.generator.classes.GodotClass, scope ref mir.serde.SerdeFlags!(godot.tools.generator.classes.GodotClass).SerdeFlags) [0x5588bba78f60]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:2901 mir.serde.SerdeException asdf.serialization.deserializeValue!(godot.tools.generator.classes.GodotClass).deserializeValue(asdf.asdf.Asdf, ref godot.tools.generator.classes.GodotClass) [0x5588bba77fb0]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:2306 mir.serde.SerdeException asdf.serialization.deserializeValue!(godot.tools.generator.classes.GodotClass[], godot.tools.generator.classes.GodotClass).deserializeValue(asdf.asdf.Asdf, ref godot.tools.generator.classes.GodotClass[]) [0x5588bba77b93]
../../../../.dub/packages/mir-algorithm/3.21.0/mir-algorithm/source/mir/serde.d:2325 mir.serde.SerdeException mir.serde.deserializeValueMemberImpl!(asdf.serialization.deserializeValue, asdf.serialization.deserializeScopedString).deserializeValueMemberImpl!("classes", asdf.asdf.Asdf, godot.tools.generator.api.ExtensionsApi).deserializeValueMemberImpl(asdf.asdf.Asdf, scope ref godot.tools.generator.api.ExtensionsApi, scope ref mir.serde.SerdeFlags!(godot.tools.generator.api.ExtensionsApi).SerdeFlags) [0x5588bba7a3c1]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:2901 mir.serde.SerdeException asdf.serialization.deserializeValue!(godot.tools.generator.api.ExtensionsApi).deserializeValue(asdf.asdf.Asdf, ref godot.tools.generator.api.ExtensionsApi) [0x5588bba73a23]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:433 godot.tools.generator.api.ExtensionsApi asdf.serialization.deserialize!(godot.tools.generator.api.ExtensionsApi).deserialize(asdf.asdf.Asdf) [0x5588bba73795]
../../../../.dub/packages/asdf/0.7.17/asdf/source/asdf/serialization.d:443 godot.tools.generator.api.ExtensionsApi asdf.serialization.deserialize!(godot.tools.generator.api.ExtensionsApi).deserialize(in char[]) [0x5588bba719c3]
modules/tools/generator/package.d:73 _Dmain [0x5588bba7ea93]`

**Comment by SpiceyWolf** [comment]
I get this error just generating bindings

**Comment by Superbelko** [comment]
Looks like merge conflict resolution fail. Will check again tomorrow.

**Comment by Superbelko** [comment]
godot-4.2 branch should work now, haven't had time to see how to fix hot reload though.

**Comment by Superbelko** [comment]
Since godot-4.2 is now merged in master I'm closing this issue as fixed. #143
Meanwhile I'll see what I can do to bring hot-reloading support.
