### ISSUE TITLE
Question - is there a way to debug the shared lib/plugin?

### ISSUE THREAD

**Issue by dsobiera** [godot-dlang/godot-dlang#140]
As the title asks, is there a way to hook up gdb to the generated .so to debug (breakpoints, stepping, etc)?

I'm using VS Code and I can debug a normal D lang program w/ the webfreak extension but I'm not sure how/if one can do this for something like this called from Godot itself.

Any advice would be greatly appreciated.

**Comment by Superbelko** [comment]
Hi, just like you normally do but specify godot as start program and pass project as parameters (exact command line can be obtained when running godot with verbose flag), you can see real examples here [1]

[1] https://github.com/godot-dlang/godot-dlang/blob/master/.vscode/launch.json

**Comment by dsobiera** [comment]
That worked perfectly.  What I ended up doing is:

    "version": "0.2.0",
    "configurations": [
        {
            "name": "Godot Debug",
            "type": "gdb",
            "request": "launch",
            "target": "/home/dsobiera/bin/godot/Godot_v4.1.2-stable_mono_linux.x86_64",
            "arguments": "${workspaceFolder}/project.godot",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText"
        }
    ]

Thank you!
