### ISSUE TITLE
Error: need `this` for `create` of type `Ref!(Image)(in long width, in long height, in bool use_mipmaps, in Format format)`

### ISSUE THREAD

**Issue by dsobiera** [godot-dlang/godot-dlang#145]
On build, I get this:

"Error: need `this` for `create` of type `Ref!(Image)(in long width, in long height, in bool use_mipmaps, in Format format)`"

The line in question is:

Image image = Image.create(1280, 720, false, Image.Format.formatRgb8);

(Image.createFromData does the same thing)

Any idea what I am doing wrong?

OS: Ubuntu 22.04.3 LTS
Godot 4.1.2
dmd: v2.105.2

**Comment by Superbelko** [comment]
Just looked up the extensions API and these two methods are indeed must be static.
It seems we have an issue with static methods in generator right now, I'll try to fix this tomorrow.

As a quick workaround you should be able to use it by manually editing the implementation (classes/godot/image.d around line 468) to something like this (notice the static and and a new temporary field. 
This code is not tested though.

```d
static Ref!Image create(long width, long height, bool use_mipmaps, in Image.Format format) {
    if (!GDExtensionClassBinding.method_create.mb) {
        StringName classname = StringName("Image");
        StringName methodname = StringName("create");
        GDExtensionClassBinding.method_create.mb = gdextension_interface_classdb_get_method_bind(cast(GDExtensionStringNamePtr) classname, cast(GDExtensionStringNamePtr) methodname, 986942177);
    }
    godot_object _godot_object;
    return ptrcall!(Image)(GDExtensionClassBinding.method_create, _godot_object, cast() width, cast() height, cast() use_mipmaps, cast() format);
}
```

**Comment by dsobiera** [comment]
I did add that and it fixed the compile time error. However, on running, when it gets to this line in my code:

Image image = Image.create(1280, 720, false, Image.Format.formatRgb8);

It exits at run time with:

src/rt/dwarfeh.d:340: uncaught exception reached top of stack
This might happen if you're missing a top level catch in your fiber or signal handler
core.exception.AssertError@../../github/godot-dlang/src/godot/api/bind.d(191): Method  called on null reference
----------------
??:? _d_assert_msg [0x7ffff2674f44]
??:? godot.api.reference.Ref!(godot.image.Image).Ref godot.api.bind.ptrcall!(godot.image.Image, godot.api.bind.GodotMethod!(godot.image.Image, long, long, bool, godot.image.Image.Format).GodotMethod, long, long, bool, godot.image.Image.Format).ptrcall(godot.api.bind.GodotMethod!(godot.image.Image, long, long, bool, godot.image.Image.Format).GodotMethod, in godot.abi.types.godot_object, long, long, bool, godot.image.Image.Format) [0x7ffff4f50508]

**Comment by Superbelko** [comment]
Yeah, I discovered that myself too when I was fixing it...

Can you try godot-4.2 branch? Don't mind the name, there is no 4.2 specific features yet so it should work with 4.1 as well, but mind that there was reference counting fixes so it might uncover some issues with memory management or just be buggy.
If you can confirm it works I think we can do a new release with fresh fixes.

**Comment by dsobiera** [comment]
The 4.2 branch doesn't seem to exist any more. Looks like maybe it was merged into master?

I tried master and things seem to work now (both compile and run).

Many thanks!

**Comment by al1-ce** [comment]
See #132 for where and what versions are now

In basic terms:
- master - 4.2 (aka current dev version)
- 4.1 - 4.1
Etc

And if issue is solved please close it
