### ISSUE TITLE
Question: PackedByteSize - What is the proper way to define

### ISSUE THREAD

**Issue by dsobiera** [godot-dlang/godot-dlang#150]
In gdscript if I do:

	var my_packed_byte_array : PackedByteArray 
	print("size = ", my_packed_byte_array.size())

I get "size  0" (which is what I expect).

But I think I'm doing something fundamentally wrong in D.  When I do this:

        PackedByteArray myPackedByteArray;
        print("in D size = ", to!string(myPackedByteArray.size()));

I get "in D size = 779192"

Can someone please point out the proper D way to define this? :)

**Comment by Superbelko** [comment]
Probably a bug in native calls, packed and typed arrays is not very well tested yet. 
I only fix stuff but don't have much time to use it in my own projects ;(

**Comment by Superbelko** [comment]
Hmm, that's strange, I tried this and it works for me, using LDC 1.35 and Godot 4.2 beta4+

```d
PackedByteArray pb;
assert(pb.size == 0);

pb.pushBack(1);
pb.pushBack(2);
assert(pb.size == 2);
assert(pb[1] == 2);

print("in D size = (str) ", to!string(pb.size()));
print("in D size = ", pb.size());
```

output
```
WARNING: in D size = (str) 2
     at: example.Test.test (examples\test\src\example.d:464)
examples\test\src\example.d:464 - in D size = (str) 2 (User)
WARNING: in D size = 2
     at: example.Test.test (examples\test\src\example.d:465)
examples\test\src\example.d:465 - in D size = 2 (User)
```

**Comment by dsobiera** [comment]
Hmmmm.

Git master 067265ca686573bacf0e1ae1b371dce20b49099e I am not getting the same results. I am running master due to the fix and merge mentioned in #145 for the static functions.

Your code runs as:

rc/rt/dwarfeh.d:340: uncaught exception reached top of stack
This might happen if you're missing a top level catch in your fiber or signal handler
core.exception.AssertError@source/testprog.d(27): Assertion failure

Line 27 is this line:         assert(pb.size == 0);

**Comment by Superbelko** [comment]
It is the same issue, assert fails because internally array contains garbage.
This is linux specific as it seems, I'll look into it tomorrow.

**Comment by Superbelko** [comment]
#151 should fix this issue

**Comment by dsobiera** [comment]
I just tried your changes and it seems to work fine now.  

Thank you!
