### ISSUE TITLE
ERROR: 'classes' dir not found

### ISSUE THREAD

**Issue by LiamM32** [godot-dlang/godot-dlang#176]
**Describe the bug**
I followed the instructions in README.md to set up the project, but when I run `dub`, I get the following error output.
```
ERROR: 'classes' dir not found, did you forgot to generate bindings?
Error Command failed with exit code 1: if [ ! -d "classes/" ]; then echo "ERROR: 'classes' dir not found, did you forgot to generate bindings?" && exit 1; fi
```

Here is the structure of relevant files:
```
├── dub.sdl # Dub config for a library I wrote that this project depends on
├── source/
└── OE-godot
    └── dub.sdl # The dub config that was being run.
    └── extension_api.json
    └── project.godot
    └── oe-godot.gdextension
    └── source/
        └── someObject.d # Just used to test Godot-dlang
```

I am using 64-bit Manjaro Linux.

The instructions don't say anything about a "classes" directory. The error remains even if I add one.

**Comment by LiamM32** [comment]
It turns out that the same error happens when I try to build the examples provided in this repository, so the file structure I provided isn't relevant.

**Comment by al1-ce** [comment]
> ERROR: 'classes' dir not found, did you forgot to generate bindings?
It says right here what's the problem

And here's how to build them
https://github.com/godot-dlang/godot-dlang?tab=readme-ov-file#generating-godot-bindings

**Comment by LiamM32** [comment]
> > ERROR: 'classes' dir not found, did you forgot to generate bindings?
> > It says right here what's the problem
> 
> And here's how to build them https://github.com/godot-dlang/godot-dlang?tab=readme-ov-file#generating-godot-bindings

I had already followed those instructions, and I just did it again. The problem persists.

Perhaps those instructions should be made more specific. They are very vague. It doesn't specify which directory everything should happen in. They are also made for Windows, which may be a problem.

**Comment by LiamM32** [comment]
I just did it again. I did the command `godot --dump-extension-api`, and then placed the new copy of `extension_api.json` exactly where it's placed in the diagram I showed earlier. Here are the entire terminal commands and outputs following this:
```
[liam@Liam-Manjaro-Desktop OE-godot]$ ls
dub.sdl              extension_api.json  icon.svg.import       oe-godot.gdextensions  source
dub.selections.json  icon.svg            oe-godot.gdextension  project.godot
[liam@Liam-Manjaro-Desktop OE-godot]$ dub run godot-dlang:generator -- -j extension_api.json -o
             Building package godot-dlang:generator in /home/liam/.dub/packages/godot-dlang/0.6.0/godot-dlang/
    Starting Performing "debug" build using /usr/bin/dmd for x86_64.
  Up-to-date mir-core 1.7.0: target for configuration [library] is up to date.
  Up-to-date mir-algorithm 3.22.0: target for configuration [default] is up to date.
  Up-to-date asdf 0.7.17: target for configuration [library] is up to date.
  Up-to-date dxml 0.4.4: target for configuration [library] is up to date.
  Up-to-date godot-dlang:util 0.6.0: target for configuration [library] is up to date.
  Up-to-date libdparse 0.20.0: target for configuration [library] is up to date.
  Up-to-date godot-dlang:generator 0.6.0: target for configuration [application] is up to date.
    Finished To force a rebuild of up-to-date targets, run again with --force
     Running ../../../.dub/packages/godot-dlang/0.6.0/godot-dlang/lib/generator -j extension_api.json -o
["/home/liam/.dub/packages/godot-dlang/0.6.0/godot-dlang/lib/generator"]
Outputting to default directory /home/liam/.dub/packages/godot-dlang/0.6.0/godot-dlang/classes...
Overwriting existing output directory '/home/liam/.dub/packages/godot-dlang/0.6.0/godot-dlang/classes'...
Done! API bindings written to '/home/liam/.dub/packages/godot-dlang/0.6.0/godot-dlang/classes'
[liam@Liam-Manjaro-Desktop OE-godot]$ dub
     Warning Selected package godot-dlang ~master does not match the dependency specification ~>0.6.0 in package oe-godot. Need to "dub upgrade"?
     Warning Invalid source/import path: /home/liam/.dub/packages/godot-dlang/~master/godot-dlang/classes
     Warning Invalid source/import path: /home/liam/.dub/packages/godot-dlang/~master/godot-dlang/classes
    Starting Performing "debug" build using /usr/bin/dmd for x86_64.
  Up-to-date godot-dlang:util ~master: target for configuration [library] is up to date.
  Up-to-date utf_bc 0.2.1: target for configuration [library] is up to date.
    Building godot-dlang ~master: building configuration [default]
   Pre-build Running commands
ERROR: 'classes' dir not found, did you forgot to generate bindings?
Error Command failed with exit code 1: if [ ! -d "classes/" ]; then echo "ERROR: 'classes' dir not found, did you forgot to generate bindings?" && exit 1; fi
```

**Comment by Superbelko** [comment]
It is supposed to work by just pointing the generator to a bindings json file, it should then place the classes in a dub project folder - somewhere in `~/.dub/packages/...` package location, or if you run it manually inside the folder containing dub.sdl file.

From your log it seems to be ran correctly, however I have no idea what's wrong with this line `Warning Invalid source/import path: /home/liam/.dub/packages/godot-dlang/~master/godot-dlang/classes`, can you check this location and make sure it has generated .d files in it?

**Comment by LiamM32** [comment]
> It is supposed to work by just pointing the generator to a bindings json file, it should then place the classes in a dub project folder - somewhere in `~/.dub/packages/...` package location, or if you run it manually inside the folder containing dub.sdl file.
> 
> From your log it seems to be ran correctly, however I have no idea what's wrong with this line `Warning Invalid source/import path: /home/liam/.dub/packages/godot-dlang/~master/godot-dlang/classes`, can you check this location and make sure it has generated .d files in it?

It didn't make a classes directory. There is no classes directory here.

Is it a problem that I put `extension_api.json` in my project directory? I put it here because I don't know where else to put it. Would `classes/` be placed in the project directory, or the same directory that `extension_api.json` was put?

Either way, it didn't make the classes directory. If this hasn't been tested on Linux recently, perhaps it can be tried on GitHub Codespaces (if all of you are on Windows).

**Comment by Superbelko** [comment]
Running the generator will place `classes` next to a godot-dlang dub package itself, e.g. `~/.dub/packages/godot-dlang/~master/classes`, or wherever you git cloned it if you go that way.
I think it should be possible to remove pre-build check and just add source paths in your dub package instead, either way should work, probably.

It is actually looks like you have `dub add`ed dependency first, and then set the version to master tag (or in reverse order), here is a hint, notice that the second call points to a different version (master vs 0.6.0):

```
Outputting to default directory /home/liam/.dub/packages/godot-dlang/0.6.0/godot-dlang/classes...
Overwriting existing output directory '/home/liam/.dub/packages/godot-dlang/0.6.0/godot-dlang/classes'...
Done! API bindings written to '/home/liam/.dub/packages/godot-dlang/0.6.0/godot-dlang/classes'

liam@Liam-Manjaro-Desktop OE-godot]$ dub
     Warning Selected package godot-dlang ~master does not match the dependency specification ~>0.6.0 in package oe-godot. Need to "dub upgrade"?
     Warning Invalid source/import path: /home/liam/.dub/packages/godot-dlang/~master/godot-dlang/classes
```

In this case I would recommend editing `dub.selections.json` in your project dir and manually set the version you want to use (0.6.0 for stable, ~master for latest changes) and run `dub upgrade` to fix it.

Or it could be the problem where multiple cached versions exists in dub cache, to be honest I have no idea how it will work in this case as I use fixed dependency path to a develop version like this (this clears the question of where the classes should be located).

__`dub.selections.json`__:
```
{
	"fileVersion": 1,
	"versions": {
		"godot-dlang": {"path":"C:/godot/bin/godot-dlang"},
		"utf_bc": "0.2.1"
	}
}
```

**Comment by LiamM32** [comment]
> In this case I would recommend editing `dub.selections.json` in your project dir and manually set the version you want to use (0.6.0 for stable, ~master for latest changes) and run `dub upgrade` to fix it.

Did it! Running `dub build` now works as it should.
