### ISSUE TITLE
Can't build without add-local

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#2]
This may be a me-problem, but I couln't build with "dub add-override" and instead needed "dub add-local" coz override was causing "unresolvable dependency" error

> I used add-local initially for tutorial, however I had godot-d 0.13 and 0.14, so it was trying to use them.
> Another option is to use local package .dub.selections.json and put paths to the repo in there.

**Comment by Superbelko** [comment]
Since now it is renamed and is on dub, is it still relevant?

**Comment by al1-ce** [comment]
Since I've added instruction for that in readme it's not really relevant
