### ISSUE TITLE
User-written scripts not registered to the GC, leading to confusing memory corruption.

### ISSUE THREAD

**Issue by dukc** [godot-dlang/godot-dlang#200]
Godot has it's own memory management, so there is no need for the D garbage collector to collect the script classes themselves.

However, consider a regular D array, allocated on the heap by the script:

```D
class MissionResult : GodotScript!Node
{   alias owner this;
    int[] hits;

    @Method void _ready()
    {   if (Engine.isEditorHint()) return;
        hits = new int[](targetNames.length);
    }
}
```

This results in memory corruption! Since the D GC doesn't know about the `MissionResult` instance, it won't find any reference to the ints referred to by `hits`, and will therefore collect them the next time it needs to collect. It's especially confusing since `hits` usually seems to work right at first, but will then get strange values and at some point crash.

Ideally, there would be a global pool of `Object` references that the GC knows about, and `createFunc` and `destroyFunc` templates would add/remove references to the scripts to/from the said pool.

Now, I understand that Godot is designed to work without a garbage collector, so it might not be desirable to do this for all scripts. I think it should be done by default, though. The times when the GC has to be avoided are relatively rare, but the dangling pointer bugs with the present situation are really likely to happen and confusing when they do. Yes, the Godot data structures are good workarounds that don't suffer from this problem, but still.

**Comment by Superbelko** [comment]
Docs should mention that all allocations should be done with `memnew`, paired with `memdelete` calls. 
There is no way to register all of Godot threads with D runtime, so any GC memory will be insta-freed.

**Comment by dukc** [comment]
> There is no way to register all of Godot threads with D runtime, so any GC memory will be insta-freed.

You're thinking about scanning the stack and thread-local storage, right? There's no need to register all threads. Only those that run D code using the GC-controlled heap.

It seems the main scene-handling thread is the same that gets registered when DRuntime is initialised. I worked around my problem by storing a reference to each `hits` array to a static `int[][]` array. That did stop the memory corruption, meaning the runtime is aware of the thread where D scripts are run. Unless I'm mistaken, Godot doesn't do any multi-threading for scripts unless explicitly told to.

As for other threads that need to use the GC-controlled heap, [`thread_attachThis`](https://dlang.org/phobos/core_thread_osthread.html#.thread_attachThis) looks to me like it'd solve the problem. It needs to be called manually by the D script running in another thread, but it's better than no GC at least sometimes.

**Comment by Superbelko** [comment]
just some thoughts:
- godot doesn't run multi-thread scripts by default, there is however some parts of the engine when it does access them from other threads
- main thread (i.e. the one which godot runs its main loop, loads extension and runs scripts) should be registered automatically by D runtime, otherwise even having static array of "pinned" pointers won't work, right?

now an interesting part

- scene nodes (any D object derived from node) actually might just work if one registers Godot's `get_tree().root` within GC https://dlang.org/phobos/core_memory.html#.GC.addRoot 
- plain Godot objects (derived from any class above Node in D) is a bit more complicated, I'm not so sure if Godot even tracks them because this is exactly what RefCounted does and plain Object has to be destroyed manually, so it seems pretty much any allocated non-Node object should be registered with GC.

**Comment by dukc** [comment]
> just some thoughts:
> 
>     * godot doesn't run multi-thread scripts by default, there is however some parts of the engine when it does access them from other threads

When [explicitly calling](https://docs.godotengine.org/en/stable/tutorials/performance/using_multiple_threads.html) the scripts from other threads, certainly. That page I linked even says it might be better to use threading facilities of the language when it's not GdScript, which seems excellent advice in case of D. But are there any other cases?

> 
>     * main thread (i.e. the one which godot runs its main loop, loads extension and runs scripts) should be registered automatically by D runtime, otherwise even having static array of "pinned" pointers won't work, right?

That's right, unless that pinned pointer array was `shared` or `__gshared`, which it wasn't. I also verified it by running `Thread.getThis.isMainThread` from a Godot script, which said "true". If the thread wasn't registered, it would have crashed since `Thread.getThis` returns null if the thread is not registered.

> 
> 
> now an interesting part
> 
>     * scene nodes (any D object derived from node) actually might just work if one registers Godot's `get_tree().root` within GC https://dlang.org/phobos/core_memory.html#.GC.addRoot

Unfortunately I don't think that works. The runtime would be aware of the root itself, and if it happens to contain any direct pointer to GC-allocated memory, that wouldn't get collected. But the pointers to other nodes still point to nowhere from perspective of the runtime, since the nodes are not controlled by the garbage collector. Thus it wouldn't recursively scan the whole tree.

Which also means my original proposal (global pool of pointers to nodes) wouldn't work. They would be "pointing to nowhere" from GC perspective just like pointers in the root node in your idea. This trick worked in my test since the pointers in the pool were pointing directly to the GC:d array, not the node.

> 
>     * plain Godot objects (derived from any class above Node in D) is a bit more complicated, I'm not so sure if Godot even tracks them because this is exactly what RefCounted does and plain Object has to be destroyed manually, so it seems pretty much any allocated non-Node object should be registered with GC.

The problem is not freeing the node in itself. Godot mechanisms for freeing that work just as well as they work for GdScript. The problem is freeing of any GC-collected memory allocated by the node. This issue applies equally to all D-written Godot objects, whether deleted with the root node, RefCounted or manually freed.

What might work is a variation of my original idea. `createFunc` and `destoryFunc`, instead of using a global pointer pool, would register/unregister the node to the GC as a root that isn't itself collected, with [`GC.addRange`](https://dlang.org/phobos/core_memory.html#.GC.addRange) and [`GC.removeRange`](https://dlang.org/phobos/core_memory.html#.GC.removeRange). That way, the GC should scan them as long as they exist, and when they get freed by Godot, regardless of mechanism, the GC is again informed.

**Comment by Superbelko** [comment]
The problem with adding bookmarks in `createFunc` is that it will make extra memory overhead, does every user really needs that? The answer is definitely no.

Therefore the suggested way is to allocate it yourself and only when needed, and while I'm not 100% sure it works every time I think regular scene nodes works fine as is.
For the rest of it even though it is somewhat cumbersome to do one can manually allocate/deallocate by using ctor/dtor.
This way it should provide fine-grained control over memory allocations without going full control freak mode as in C++.

Now there is another concern, adding infinitely large number of small memory ranges may or may not actually destroy performance, so the common practice anyway is to pool things(pool buffer, arena allocators, etc...), and this is somewhat orthogonal to pinning by default proposed to do on object creation in `createFunc`.

I mean if there is a solution that just works for everyone than sure I'm all in for it, but there is just too many tradeoffs that i'm still not aware of.
So, am I wrong?

**Comment by dukc** [comment]
> I mean if there is a solution that just works for everyone than sure I'm all in for it, but there is just too many tradeoffs that i'm still not aware of.

Ultimately I think it depends much on what DRuntime does. It's supposed to scan it's internal list of `addRange`d memory ranges just like it'd scan a `shared void[][]` - so there is no reason why it should be much slower than a custom pointer pool would be. But it's possible it's not implemented efficiently - even if the scanning itself is, maybe adding and removing the ranges isn't.

But I also think that if the scripts can be scanned, even with a cost of some efficiency (not meaning total destruction of it), it's worth it. GdScript is almost entirely memory safe to use: even if you use a freed Godot object, you will get a principled error as opposed to random crashes and memory corruption that's the case with cstdlib `free`. This means there's potential to bring the same safety to D scripts, as long as the user stays within `@safe` D. Of course, godot-dlang isn't currently annotated as safe, but the potential is there and even without actually using the attribute it'd work quite well in practice. But this requires there are no footguns with using the GC normally.

But I agree that that there should probably be an UDA for turning the GC scanning off for that script.

> So, am I wrong?

It's not right nor wrong, it's a design decision. Since you're the main developer, it's what convinces you that should ultimately get in, not what convinces me. I can post opinions but I understand that it's you picking the direction in the end.

I will read the DRuntime source code and post a further opinion on using `addRange`/`deleteRange` later, unless you immediately decide against using them.

**Comment by dukc** [comment]
Investigation done!

DRuntime internally uses treaps to store the scan ranges. This is definitely scalable, since the treaps are linked tree type structures, so there will never be massive reallocations all at once that would be the case were the ranges stored in monolithic arrays. But it does call `malloc` or `free` each time a scan range is added or removed, so it looked like pretty slow at small scale to me. How much? I decided it was best to stop guessing and benchmark it instead. You can check and redo the tests yourself if you think I got something wrong:

```D
import core.memory : GC;
import std;
import std.datetime.stopwatch : StopWatch;

static import cstd = core.stdc.stdlib;

void main(string[] args)
{   // When true, we simulate using addRoot for Godot.
    // When false, we benchamark using our own pointer pool
    //   instead for comparison.
    bool useRangeAdder = {
        if (args.length != 2) throw new Exception("Two arguments please!");
        return args[1].to!bool;
    }();

    StopWatch timer;

    // Half a million void arrays, their contents simulating our Godot objects.
    // Not scanned by the GC, because it's allocated with malloc.
    auto unscannedList =
        (cast(void[]*) cstd.malloc(0x8_0000 * (void[]).sizeof))[0 .. 0x8_0000];

    // An array would be unrealistic as a general-purpose pointer pool
    // because it doesn't lend itself to removing
    // items efficiently from the middle. I believe this
    // would be a better choice.
    auto pointerPool = new RedBlackTree!(void*);

    timer.start();

    if (useRangeAdder) foreach(ref item; unscannedList)
    {   // Manually allocate the "Godot object"
        item = cstd.malloc(64)[0 .. 64];
        (cast(ubyte[]) item)[] = 0;

        // Add it manually to GC as a place to scan.
        GC.addRange(item.ptr, item.length);
    } else foreach(ref item; unscannedList)
    {   // Allocate the "Godot object" by GC, because it wouldn't get scanned
        // if we mallocated it.
        item = new void[](64);

        // Copy the pointer to it to the pool so the GC will find it.
        pointerPool.insert(item.ptr);
    }

    writeln("Allocations took ", timer.peek);
    timer.reset();

    GC.collect();
    writeln("GC took ", timer.peek);
    timer.reset();

    // now we deallocate every other object
    if (useRangeAdder) foreach(ref item; unscannedList.stride(2))
    {   GC.removeRange(item.ptr);
        cstd.free(item.ptr);
        item = null;
    } else foreach(ref item; unscannedList.stride(2))
    {   pointerPool.removeKey(item.ptr);
        item = null;
    }

    writeln("Deallocations took ", timer.peek);
    timer.reset();

    GC.collect();
    writeln("Another GC took ", timer.peek);
}
```

Result:

```bash
$ dmd -O -run app.d true
Allocations took 92 ms, 119 μs, and 5 hnsecs
GC took 27 ms, 459 μs, and 7 hnsecs
Deallocations took 64 ms, 513 μs, and 1 hnsec
Another GC took 22 ms, 474 μs, and 7 hnsecs

$ dmd -O -run app.d false
Allocations took 257 ms and 354 μs
GC took 39 ms, 265 μs, and 7 hnsecs
Deallocations took 46 ms, 926 μs, and 3 hnsecs
Another GC took 19 ms and 850 μs
```

it seems that `addRange` / `removeRange` are actually _faster_ than a pointer pool would be! Plus, in this test the pointer pool actually has an advantage, because it doesn't have to be thread-safe, unlike the treaps at DRuntime, or a real pointer pool that was designed to work from many threads.

For me it seems `addRange` and `removeRange` are not going to cause any more performance trouble than the GC in general does.

**Comment by Superbelko** [comment]
Ok, thanks for your time on this investigation.

I think we can add new attribute to let `createFunc`/`destroyFunc` knows if memory should be added to GC scan, this way users will be able to control it AND this will be purely in opt-in manner.
Can't say if this is going to be safe, because for example any integer may cause false positives???

However there is few things I still don't understand about your specific issue, you say that regular D array in your GodotScript is "lost", however as long as your script entity is alive it means the array is still referenced by that object even though GC is not controlling the object itself. 

Now how does `GC.addRange(p, len)` will help in this case if there is this line in the docs about it?
>  if p points into a GC-managed memory block, addRange does not mark this block as live. 

Sure it doesn't mentions non GC-managed memory as it has no control over it and it has different purpose but still.

**Comment by dukc** [comment]
> Can't say if this is going to be safe, because for example any integer may cause false positives???

Yes it is - and this is normal! At least formerly the D garbage collector was conservative, which means it just treats everything as a pointer (unless it can forgo scanning the memory area completely - think a character array, for example). A non-conservative GC is called "precise" - there have been efforts to make D GC precise but I'm not sure how that's going and if it's currently the default. Anyway, it has been conservative for most of D history without being a major problem. A conservative GC just means the object will sometimes not be freed at the first possible collection. It might in rare cases cause problems with memory leaks but it's not a memory safety problem.

> you say that regular D array in your GodotScript is "lost", however as long as your script entity is alive it means the array is still referenced by that object even though GC is not controlling the object itself.

The GC starts by scanning the stack, thread-local storage (meaning static and global variables), shared variables and all `addRange`d memory. When it comes across a pointer:

1. if it points to a memory area allocated by the GC, it scans that too (unless it's typed as something that doesn't contain any pointers).
2. If it points somewhere else, it ignores it. This includes pointers to `malloc`ated memory or other foreign memory allocation schemes.

Since the Godot object is allocated and deallocated by Godot, not by the D GC, it will not get scanned regardless of whether there are pointers to it. It will get scanned only if it is in the stack (meaning instanced there, not just referred to from there), or global memory, or `addRange`d to the GC.

> if p points into a GC-managed memory block, addRange does not mark this block as live.

This means that `addRange` will not prevent the added memory itself getting garbage collected if it is allocated by the garbage collector. `addRange` is primarily meant for non-GCd memory anyway. If you wanted to "pin" something you allocated with the GC, `addRoot` would be a better choice.

**Comment by dukc** [comment]
Otherwise agreed, but it seems better than scan would happen by default, attributes (whether global or per-range, or both) would opt out. Avoiding the GC is kinda an advanced topic that's not often needed, but no-one want's bugs like what this topic is about. Better beginner-friendly by default.

But regardless of the default, it at least solves the issue so it's not like I'd be unhappy if you disagree.

**Comment by Superbelko** [comment]
Yeah, I decided to go with in enabled by default.
Also I haven't thoroughly tested yet but it seems like this fixed an issue in my own scripts where suddenly part of a string got overwritten by another thread (usually just few chars in front but this destroys the paths) even though that script is protected with mutexes.

**Comment by dukc** [comment]
Great!
