### ISSUE TITLE
4.3: Allow GDExtensions to register virtual methods and call them on scripts

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#206]
Original Godot PR

https://github.com/godotengine/godot/pull/87758

C++ implementation (oh god it's a lot):

https://github.com/godotengine/godot-cpp/pull/1377

**Comment by Superbelko** [comment]
Ok, seems like I get it working but the convenience is... not there.

Right now the whole thing looks like this, I will move this handle to a object but the rest is just sucks as in C++

```d
class TestVirtualMethod : GodotScript!GodotObject {

    @Method @Virtual
    String doStuff() {
        return String("This method should be overriden");
    }

    @Method void test() {
        String ret;
        if (vcall!doStuff(_gdextension_handle(), ret)) // <-- LOOK HOW THEY MASSACRED MY BOY!11
            print(ret);

        assert(ret == String("I am overriden"));
    }
}
```
