### ISSUE TITLE
Hot reloading gdextension

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#26]
Need to look if it's even possible to detach/reload extension
Most of the time Godot actually locks library and you need to quit it before successfully compiling

**Comment by Superbelko** [comment]
`NativeExtensionManager` script class has `load_extension\reload_unload\unload_extension`, just no UI for that in editor yet. Haven't tested it myself, probably will also result in crash on unload because D runtime will release used memory ;)

(just a side note: it's not the godot locks DLL it's a Windows way of working with shared libs, unlike on linux it is not fully loaded in memory in process space but instead is memory mapped, hence why the file is locked)

**Comment by al1-ce** [comment]
I'll try looking into NativeExtensionManager later
Theres much more stuff to do before that, but I might quickly stuff some plugin so it's not gonna be so tedious

I know about windows being /bad word/, me saying "godot locks" means "godot loads, windows locks". But since most of ppl use windows this needs to be fixed soon, at least for testing purposes

**Comment by Superbelko** [comment]
I did very basic test and it 'almost' works, it does unloads and loads D DLL, however godot-dlang does not unregistering scripts yet.

test script for mini guide project, run through script editor->File->Run (Ctrl-Shift X)
```gdscript
@tool
extends EditorScript

var dplugin: String

# Called when the node enters the scene tree for the first time.
func _run():
	dplugin = "res://mydplugin.gdextension"
	var ext = dplugin
	print (NativeExtensionManager.is_extension_loaded(ext))
	if NativeExtensionManager.is_extension_loaded(ext):
		NativeExtensionManager.unload_extension(ext)
		print("unloaded ext: ", ext)
	else:
		NativeExtensionManager.load_extension(ext)
		print("loaded ext: ", ext)
```

**Comment by al1-ce** [comment]
https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html

This might help with `-s` option, but I can't find any mention if there's a way to pass it into already open editor

**Comment by Superbelko** [comment]
I am currently working on editor network host plugin and godot-d subpackage that will handle load/unload for build process.

**Comment by Superbelko** [comment]
Some initial progress in #44

**Comment by Superbelko** [comment]
@al1-ce hey can you merge #44 ? 
Though it still probably requires implementing actual extension unregistering process.

**Comment by al1-ce** [comment]
U can't merge PRs?

**Comment by Superbelko** [comment]
I can, just to be sure I'm not messing up with your work, even though there is only readme and dub.json edits.

**Comment by al1-ce** [comment]
Fair enough
But rn I'm fighting with windows tho

And any big changed I'd hang in PR for some time or push them into branch

**Comment by al1-ce** [comment]
https://github.com/godotengine/godot-cpp/pull/1200

Well, this makes this issue much easier

**Comment by Superbelko** [comment]
Just a note to self, kind of a plan:

1) Implement https://github.com/godotengine/godot-cpp/pull/1200
2) > Add `reloadable = true` to your .gdextension file
3) try it
4) ... if stuck see discussion https://github.com/godotengine/godot/pull/80284

**Comment by Superbelko** [comment]
Godot 4.2 is out, and we have very basic support for extension reloading, godot will call property setters for you, and for now there is not much more can be done.
We will see how Godot will evolve with regard to hot reloading, but let's keep this issue for some a week or two.

**Comment by Superbelko** [comment]
Closing this as completed.
