### ISSUE TITLE
Cannot get Spriteplayer when class name is SpritePlayer

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#3]
It seems that godot internally expects class with wierd capitalisation

> It could be really how bindings works, when I was messing with that I haven't had any issues with script name cases.
> godot-d however translates between naming schemes when passing stuff back and forth.
> However one can use `@Rename` UDA to force a specific name in many cases.
> Needs more testing.

**Comment by al1-ce** [comment]
Closing in favour of #84

**Comment by Superbelko** [comment]
Actually I tested this just now and it works as expected with RC1, so I guess it was no longer relevant anyways.

```d
@OnReady!"Animatedsprite2d" AnimatedSprite2D Animatedsprite2d;
```

**Comment by al1-ce** [comment]
It should be
```
@OnReady!"AnimatedSprite2D" AnimatedSprite2D animatedSprite2D; 
```

Coz when I got this issue it was not me doing things with wierd case, but rather godot on registration completely disregarding any capital letters except
Just like in #84

**Comment by al1-ce** [comment]
So, #84 is just duplicaye of this one, but my issue u opened is better then this one and so I closed this one in favour of new

**Comment by Superbelko** [comment]
> It should be
> 
> ```d
> @OnReady!"AnimatedSprite2D" AnimatedSprite2D animatedSprite2D; 
> ```
> 
> Coz when I got this issue it was not me doing things with wierd case, but rather godot on registration completely disregarding any capital letters except first one Just like in #84

Tried this now, still works fine, so probably it is was just some minor bug in godot itself back then.
