### ISSUE TITLE
All scripts are running as tool (Not fixable yet due to GDExtension logic)

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#4]
This is more of gdextension problem, but having wall everything in "!Engine.editorHint" is quite daunting
> GDExtension has concept of initialization levels, IIRC this can be done by moving class registration into specific init level, need further investigation.

**Comment by al1-ce** [comment]
https://github.com/godot-dlang/godot-dlang/blob/master/src/godot/api/register.d#L130-L132

Found place where initialization begins.
Also looking at https://docs.godotengine.org/en/latest/classes/class_nativeextension.html
We might pull out this part, though I'm not sure 
```
enum InitializationLevel:
INITIALIZATION_LEVEL_CORE = 0
INITIALIZATION_LEVEL_SERVERS = 1
INITIALIZATION_LEVEL_SCENE = 2
INITIALIZATION_LEVEL_EDITOR = 3 
```

Though taking a peek at gdextension module shows that initialization levels should be same as shown in gddocs
https://github.com/godot-dlang/godot-dlang/blob/master/src/godot/abi/gdnative_interface.d#L598-L606

Not sure why it's not working as intended, but I assume we better change it some of those things (in gdextension.d) to generated NativeExtension class

**Comment by Superbelko** [comment]
Just a note, godot-cpp works exactly the same, even though it sets initialization level to scene it still calls _ready in editor. So it is either expected behavior in Godot 4 or they still haven't implemented that init level separation.

**Comment by al1-ce** [comment]
I don't think that this should be expected

Maybe it's a bug in gdextension... 
Or they want to change init levels soon, who knows

**Comment by al1-ce** [comment]
I think I found how to solve it in somewhat easy way, no passing anything to godot, just check on our side if something is `@Tool` and what level godot is in

https://github.com/godotengine/godot-cpp/blob/master/test/src/register_types.cpp#L19-L35

**Comment by Superbelko** [comment]
Nope, godot-cpp works same way with GDEXTENSION_INITIALIZATION_SCENE, I also thought in our case code runs inside GDEXTENSION_INITIALIZATION_EDITOR, but after stepping through with debugger it is actually was correct.

**Comment by al1-ce** [comment]
From issue on C++ bindings:

---

Unfortunately, this is not what MODULE_INITALIZATION_LEVEL_SCENE and MODULE_INITIALIZATION_LEVEL_EDITOR are for. Just like in Godot modules defined in the engine, any nodes that are registered during any initialization level will run in the editor, and they need to call Engine::is_editor_hint() to control what behavior they want to run in editor or not. In general, GDExtensions aim to emulate how Godot modules work, and this is how it works for Godot modules.

The initialization levels have to do with the process of engine startup, so that things are registered in the right order. For example, some aspects of the editor need to be initialized before we can start registering editor-related classes.

---

That explains why, but, unfortunately, not how to fix it

**Comment by Superbelko** [comment]
Godot 4.3 dev4 now introduces the concept of non-tool classes, https://github.com/godotengine/godot/pull/82554 this PR adds new registration function and "runtime" flag for that.

I will look into it and try to make this change into v0.7.0 with version condition, the question is should we just make this new default or just add another class attribute like `@RuntimeOnly` or maybe the opposite like `@Tool` to reflect GDScript?

**Comment by Superbelko** [comment]
Because this is the default in GDExtension, breaking everything and invert that requirement by adding `@Tool` explicitly is already too late for Godot 4.

**Comment by al1-ce** [comment]
I mean, technically having, idk, checking for `version(DEFAULT_RUNTIME)` in where it matters with you explicitly needing to enable it would be better choice imo
And then instead of defining runtime classes, you'd define tool classes

**Comment by Superbelko** [comment]
Version creep is no joke.
The decision was made and no code was broken, plus users now have a way to opt out.

**Comment by al1-ce** [comment]
I don't agree, option to opt-in or opt-out is better, but ok
