### ISSUE TITLE
Godot 4 Rust bindings out

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#45]
https://github.com/godot-rust/gdextension

Might be useful to look at their implementation

**Comment by al1-ce** [comment]
Fun fact. They use GodotString for some parts and native strings for other. Not a template conversion though, `"string".into()".
Also they use structs for Godot node types and very wierd way to derive them

**Comment by Superbelko** [comment]
Just from the description it looks not very user friendly, also

> You need to have LLVM installed to use bindgen, see [the book](https://godot-rust.github.io/book/getting-started/setup.html#llvm) for instructions.

Seriously? I guess Windows is not their target platform then...

Tbh I also looked in the past at godot-nim, but its syntax is too much for my eyes.

**Comment by al1-ce** [comment]
Yea.. Rust isn't prettiest of them all
It's like if c++ and typescript had a baby and it got worst of their syntax

And what's wrong with LLVM? It's perfectly usable on Windows

**Comment by SpiceyWolf** [comment]
Alot of weird stuff they do in the rust that may subvert your expectations is going to be them attempting to optimize for the languages 'lifetime' behavior cause safety is their deity.

**Comment by al1-ce** [comment]
Well, godot-d was that way too. `gs!"string"` and `GodotScript!NodeType` are kind of still here because of that
