### ISSUE TITLE
Asteroids demo broken?

### ISSUE THREAD

**Issue by Superbelko** [godot-dlang/godot-dlang#46]
Not sure exactly what's going as I have two godot versions, one is built from source and official beta4 release.

`_process()` method crashes (null reference), it is also called in editor and needs editor hint check.

`addAsteroid()` method crashes, `Rock.tscn` resource seems to be loaded ok but then cast to PackedScene returns null.

**Comment by al1-ce** [comment]
On my c# project I'm still sitting on beta 1 coz opening it in others crashes godot without any logs or errors
Same for asteroids

Probably need to check it all one by one starting from packed scene

Also it seems godot changed delta to double, can it cause any troubles?

**Comment by Superbelko** [comment]
It is a double in this bindings by default as their official builds is now using DOUBLE_PRECISION(or what it is now) build settings.

The main problem with asteroids is this packed scene.

**Comment by al1-ce** [comment]
It might be godot or it might be extension
Have u tried opening only this scene in editor?
Coz beta builds have nasty case of crashes

**Comment by Superbelko** [comment]
Yeah that why I described these issues, it crashes in editor because in _process() there is null reference of player or something so need to add `is editor` check, next I tried to run actual game and got crash because packed scene was null. 
Stepped in debugger and it seems godot itself does return valid asset so looks like casts broken in D but I haven't debugged it thoroughly yet because in VSCode it doesn't work well with structs.

**Comment by al1-ce** [comment]
I'll look into that

I think I might've broken something with my string shenanigans

**Comment by Superbelko** [comment]
In debugger I have something strange going on in basecasts(), it falls through to init return. But then even if bypass it altogether and just use raw scene pointer in scene.instantiate() the `rock` variable is still null.

https://github.com/godot-dlang/godot-dlang/blob/e050a2f5c9b153f36ef2813eed89caf23c4a2e23/src/godot/api/bind.d#L293

**Comment by Superbelko** [comment]
Yeah, it is not only asteroids, the test project is not updated at all.

It also shows that generator doesn't emit original String/StringName variants and only plain string helpers. Imagine a method returning StringName, what should I do with it now?

**Comment by al1-ce** [comment]
How the hell did i not notice that. Merged. 

good work

**Comment by Superbelko** [comment]
It looks like the problem was in string conversions, now I need to fix infinite loop in StringName construction.

**Comment by al1-ce** [comment]
I think length method is a problem

**Comment by Superbelko** [comment]
Yeah, but anyway it should now work, however in asteroids demo input still not working, but this is probably because of beta4.

btw beta5 is now out.

**Comment by al1-ce** [comment]
Yay, more breaking changes

Btw ur a saviour and I'm currently distro hoping, stopped at manjaro, feels nice. Gonna provide linux tests

**Comment by al1-ce** [comment]
GDExtension: Use StringName in GDExtension perf critical instance creation & method/properties setter/getter (GH-67750).

That's interesting one

**Comment by al1-ce** [comment]
I better change readme to use non-certain beta release. Changing it every two weeks would be kinda meh

**Comment by Superbelko** [comment]
This is funny because there is tons of overhead for marshalling data back and forth, just that one thing makes me skeptical about using extensions at all.

**Comment by al1-ce** [comment]
Well, if not extension then what? Half of somewhat mature game engines use c# as their language, thanks to unity, and c# isn't the brightest of all languages. Unreal has blueprints, but blueprints are for uncool, also unreal uses c++, but it supports it so badly it's starting to be sad.
Other engines are working 50% of time and many of them use c++, but it's hell to work with. And using libs is real unfiltered pain (that's why I'm not even touching dagon), just as making ur own engine.
Godot is the best one of them coz it allows to use something you like, someone just needs to work on it and if gets enough traction (like js) bindings do themselves

**Comment by Superbelko** [comment]
Yeah, I know. Godot now goes the Unreal Engine way, and in fact with some f...ery it is possible to craft something like godot-d for unreal. 
Not that I'm willing to do so in any foreseeable future. So for now sticking with godot.

**Comment by al1-ce** [comment]
Tbh unreal viable only if you're aiming for realistic graphics or insanely bloom heavy game

**Comment by Superbelko** [comment]
Fixed input and visual #54

With beta5 though it now crashes on extension unload.

**Comment by Superbelko** [comment]
Closing this as no longer relevant, after fixing #74 it seems to work adequately.
