### ISSUE TITLE
StringName does not work as intended

### ISSUE THREAD

**Issue by Superbelko** [godot-dlang/godot-dlang#52]
It is supposed to be hashed value for quick comparison, it works to some extent, however when received StringName from godot with say method name to call their values are different, thus defeating their intended role.

It could be D vs godot unicode encoding differences (even though method names are in plain ASCII subset) but I really have no idea what's going on.

**Comment by al1-ce** [comment]
I'm thinking to partially get rid of automatic StringName to string conversion
Mainly in returns

**Comment by SpiceyWolf** [comment]
https://godotengine.org/en/article/dev-snapshot-godot-4-0-beta-9

They made string and stringname more compatible, do you see this possibly improving the situation here if they extend that to the gdextension counterpart?

**Comment by Superbelko** [comment]
Could be related to this [Breaking news: std.uni changes!](https://forum.dlang.org/post/mzaeiftqskukumkpbfeo@forum.dlang.org)

In short: Unicode 6.2 in D versus 15.0 current standard version, D Unicode support hasn't been updated for 10 years.

**Comment by Superbelko** [comment]
Since godot-4.2 it is now used in onReady wrapper instead of hacky variant to string casts and does seems to work as expected, fixed in #143
