### ISSUE TITLE
gdextension headers breaking bind templates

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#57]
@Superbelko new commit https://github.com/godotengine/godot-headers/commit/dfdf91336a50b2af4154beef853fdc75ae303666 turns `GDNativeMethodBindPtr` from `void*` into `const(void*)`.
This brakes `GodotMethod!` template since it has `GDNativeMethodBindPtr mb`, which is not const. 
And it also tries modifying it with `mb = _godot_api.classdb_get_method_bind(cast(GDNativeStringNamePtr) StringName(className), cast(GDNativeStringNamePtr) StringName(methodName), hash);`, which is not acceptable

**Comment by al1-ce** [comment]
Added new branch in this commit https://github.com/godot-dlang/godot-dlang/commit/8cb31865f0d6ce660e483e8dfd52654d13e1ec86

**Comment by Superbelko** [comment]
then don't mark it const on our side, it is not part of name mangling scheme in C so who cares. 
btw it translates as const(void)* which still allows reasign but prohibits messing with the value itself, though I don't remember if it is actually works with void

**Comment by Superbelko** [comment]
I think this can be closed now, time showed us that there is no issues with this change, if this is still a problem with ImportC headers it is then a bug with ImportC incorrectly translates types and we already have dedicated issue open.
