### ISSUE TITLE
Hash mismatch for Input class

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#6]
Basically every method of Input has a hash mismatch
> This is actually a godot issue, it was like that since early alpha. IIRC same with official godot-cpp.

**Comment by al1-ce** [comment]
Happens from time to time on different classes, sometimes blocks usage of said class

**Comment by Superbelko** [comment]
Probably this (#89) fixed it.

**Comment by Superbelko** [comment]
Closing this as fixed by #89
