### ISSUE TITLE
Variant broken

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#60]
https://github.com/godot-dlang/godot-dlang/blob/25c00a60832585fe766ef1f269754450a2bc0d9b/src/godot/variant.d#L489

`` src/godot/variant.d(489,49): Error: no property `variant_as_vector3` for `_godot_api` of type `godot.abi.gdextension.GDNativeInterface*` ``

**Comment by Superbelko** [comment]
Is this even needed now? I mean it was for years now, this compiler bug could be already fixed long ago.
Besides GDExtensions has changed how these values are passed.

**Comment by al1-ce** [comment]
Need to look what the heck it actually does
But yea, I guess it could be yeeted

**Comment by SpiceyWolf** [comment]
Was this not basically just yeeted earlier today?

**Comment by Superbelko** [comment]
Tested with LDC 1.30 and DMD 2.102, variant containing vector3 works fine on both Linux and Windows.
Closing this issue as no longer relevant.
