### ISSUE TITLE
Sync with GDNative -> GDExtension rename (beta10)

### ISSUE THREAD

**Issue by Superbelko** [godot-dlang/godot-dlang#62]
Commit on December 7th renames all the occurrences of GDNative, need to do the same in our code.

I am already working on this in order to update for beta10.

**Comment by al1-ce** [comment]
Im gonna try to do #61 soon, it might solve a lot of inconvenience with tracking changes, tho we will still need to track them, but only for changing godot.abi symbols

**Comment by Superbelko** [comment]
Better wait for this update, there is changes all over the sources...

**Comment by Superbelko** [comment]
Should be done now, it seems there was also changes in extension dump structure and now I have this error, looks like enum is gone or moved somewhere else

> classes\godot\navigationagent2d.d(50,41): Error: undefined identifier `NavigationPathQueryParameters2D.PathMetadataFlags

**Comment by Superbelko** [comment]
Oops, a typo, @al1-ce can you fix it while you work on your problem? I should go now :(

https://github.com/godot-dlang/godot-dlang/blob/dcb42867efcc2866e2b06763fff1237ae9addd8c/src/godot/api/register.d#L295

**Comment by al1-ce** [comment]
Okie

**Comment by Superbelko** [comment]
Fixed with #64
