### ISSUE TITLE
Godot Beta 12

### ISSUE THREAD

**Issue by SpiceyWolf** [godot-dlang/godot-dlang#65]
Only just had the opportunity to try getting setup after a good few versions. Beta 12 doesnt have any errors on the generator but the 'use-in-project' throws these errors (Made from ~master)

\godot-dlang\src\godot\navigationagent2d.d(50,41): Error: undefined identifier `NavigationPathQueryParameters2D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent2d.d(51,41): Error: undefined identifier `NavigationPathQueryParameters2D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent2d.d(346,7): Error: undefined identifier `NavigationPathQueryParameters2D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent2d.d(357,52): Error: undefined identifier `NavigationPathQueryParameters2D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent2d.d(572,62): Error: undefined identifier `NavigationPathQueryParameters2D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent2d.d(576,17): Error: undefined identifier `NavigationPathQueryParameters2D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent3d.d(54,41): Error: undefined identifier `NavigationPathQueryParameters3D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent3d.d(55,41): Error: undefined identifier `NavigationPathQueryParameters3D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent3d.d(394,7): Error: undefined identifier `NavigationPathQueryParameters3D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent3d.d(405,52): Error: undefined identifier `NavigationPathQueryParameters3D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent3d.d(630,62): Error: undefined identifier `NavigationPathQueryParameters3D.PathMetadataFlags`
\godot-dlang\src\godot\navigationagent3d.d(634,17): Error: undefined identifier `NavigationPathQueryParameters3D.PathMetadataFlags`

[Edit 1]:
Investigated -> The generated modules are missing the imports to:

        import godot.navigationpathqueryparameters2d;
        import godot.navigationpathqueryparameters3d;

[Edit 2]:
src/api/register.d -> line 295

        GDExtensionExtensionClassCallVirtual
    
The above seems to have slipped under the radar on the update that changed that to GDExtensionClassCallVirtual
    
Beyond that, things build just fine!

**Comment by Superbelko** [comment]
Are you sure it is on master? 

src/api/register.d:295 was already fixed last week
https://github.com/godot-dlang/godot-dlang/blob/23078337ae30a94e384f2b4e51a6fd01373c8d91/src/godot/api/register.d#L295

But the generator now has another bug where it imports non-existing global enums by name, I was hoping to fix that today but it seems it requires some extra work.

**Comment by SpiceyWolf** [comment]
I WAS using master... seems like dub wouldnt update it in place... manually nuked it and is all good now :O Sorry bout that.

**Comment by Superbelko** [comment]
Just a note, you probably need to run `dub upgrade` to fetch new packages versions, this should update all dependencies including fetching new git branches.
