### ISSUE TITLE
Static doesnt expose function, RC1 is released and crashes again.

### ISSUE THREAD

**Issue by SpiceyWolf** [godot-dlang/godot-dlang#76]
Is there a meens of doing static methods in classes? The examples dont showcase one... Im trying to make a utility class in DLang to expose to gdscript.

**Comment by Superbelko** [comment]
Plain static method marked as `@Method` should work, if not - we forgot to expose them when it was recently added.

**Comment by SpiceyWolf** [comment]
it should just be like a normal static method? Like this? `@Method static void print_hello() { print(gs!"hello world!"); }`
If so, then it def isnt expose cause when I tried exactly that, godot stops recognizing the functions even in there.

**Comment by SpiceyWolf** [comment]
Figured since I was going to post about a new issue I would do that here. RC1 dropped yesterday, and theres only 1 syntactical bug from the new update, + godot crashes again when loading the binary. The new bug is 
`.dub/packages/godot-dlang-master/godot-dlang/classes/godot/editorexportplugin.d(321,18)`

It is generating 'in bool debug' and the debug keyword is where it breaks down. On my own thing just to get passed it (since I dont really understand how the generation stuff is being done, i just mod the generated stuff) i prefixed it with `_`. Beyond this theres no more errors to compile, but there is an immediate crash.

Im gunna look at the last couple of commits and try to get an idea how you've been getting some stuff done, but if you could gimme a run down how you figured out what the problem was despite the crashing thing last time -- like the process of doing that, I'll try to start being useful and submitting patches myself lol

**Comment by Superbelko** [comment]
A bit busy atm, #77 adds RC1 support, gtg brb
static methods took more than 5 minutes as I was expecting, more like a hour, will do later

**Comment by Superbelko** [comment]
Static methods are now implemented with #78 

Example:
https://github.com/godot-dlang/godot-dlang/blob/ba30a5861a46225396eb9f95b5815ee75d62be04/examples/test/src/example.d#L133-L134

**Comment by SpiceyWolf** [comment]
works great :P

Unrelated question... any idea how to use extra dll reqs with it?

For example... I have a second lib made in D with the betterC flag because I have it available for a plugin system (can use other langs for the plugins) -> If i link that up I cant load it into godot and im not exactly sure as to why >.> I assumed it needed those deps in project root or something, but whether I put em with the binary or in root, it seems to do nothing x-x

**Comment by Superbelko** [comment]
No idea, the only thing that comes to mind is to check what LD_LIBRARY_PATH godot sets up for loading, make sure your .so dependencies are also in that path (because on Linux D links libphobos2.so dynamically by default and your library might fail because of that).

Looks relevant
https://github.com/godotengine/godot-docs/issues/2443

https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/custom_modules_in_cpp.html#improving-the-build-system-for-development

> Once compiled, we should end up with a bin directory containing both the godot* binary and our libsummator*.so. However given the .so is not in a standard directory (like /usr/lib), we have to help our binary find it during runtime with the LD_LIBRARY_PATH environment variable:

```
export LD_LIBRARY_PATH="$PWD/bin/"
./bin/godot*
```

**Comment by SpiceyWolf** [comment]
Didnt quite know this existed, was the best workaround instead of more build-script-y stuff or shenanigans loading godot (and godot extra-loading env variables wouldnt work)

this RPath thing... totally fixed it by putting it in my lib loaded by godot :D
