### ISSUE TITLE
[LDC2] Array.slice return value issue in api.bind.callBuiltinMethod()

### ISSUE THREAD

**Issue by Superbelko** [godot-dlang/godot-dlang#91]
It looks like return address doesn't passed back meaning there is potential ABI problems with LDC, it works if I use godot_array instead of Array, need to investigate.

__edit__:
After debugging it looks like in callBuiltinMethod taking address of `&ret` and `&ret._godot_array` yields the same address in DMD, but not in LDC where it seems to take stack pointer rather than the first member of Array and so deeply inside godot this points to a wrong level in Array::slice()  _(where `this` now actually should be `&this`)_

This can be hot patched with a said hack, or a better solution would actually be to unify how these wrappers types work (also will help a bit to relax generator mess), because now I expect there would be same issues with `Dictionary`, `Callable` and what other thin wrapper types out there.

Another problem is that we now have various semantics - raw pointer for strings, godot_object opaque pointer, array and others, a vector and other primitive types. 
It was implemented on top of existing old codebase and Godot 4 completely changed many of such low level concepts, so I think a real solution would be to introduce aliases in said types and do something like that

__api/bind.d__:
```d
Return callBuiltinMethod(...) {
  Return.InteropType ret; // where InteropType is for example "alias InteropType = godot_array;" in Array type
  //...
  return Return(ret);
}
```
---

__edit2__:

It seems that LDC problem is that it returns array in `rax` register and then clears out `this`(rcx) with dtor, that array in rax is an empty array and rcx is zeroed by dtor, and thus the returned value is now gone.
DMD however seems to return struct in `rdx`, IIRC this is MS calling convention, so maybe LDC doesn't follow it in this case, if that's the case then it is LDC bug.

**Comment by al1-ce** [comment]
That's a lot of problems with ldc tbh

**Comment by Superbelko** [comment]
LDC is a must for shipping code to prod.

So, what the other problems?

**Comment by Superbelko** [comment]
In the end I decided to clean up hacks and keep things as is, meaning less templates to deal with, the problem with originally proposed approach is that callBuiltinMethod() deals with mixed semantics - pointers, structs, POD types like vectors... simply adding an alias to opaque type won't help, so I choose lazy fix.

Closing as completed #95
