### ISSUE TITLE
Time for v0.2?

### ISSUE THREAD

**Issue by Superbelko** [godot-dlang/godot-dlang#94]
I think it would be a great thing to increase our visibility in dub last updated list.

Fixing #41 and #91 would be a good moment to do so.

**Comment by al1-ce** [comment]
Agreed

**Comment by SpiceyWolf** [comment]
just a suggestion on the topic of version bump, yall should have the default repo have a pregenerated run in the dub package when 4.0 goes stable so just including the godot-dlang package is enough to start using it, but if someone fiddles with another version they can manually regenerate it.

**Comment by Superbelko** [comment]
I don't think so, it will bloat this repo, it is already over 10 Mb of generated data. 
Maybe a dub prebuild step that checks and generates everything automatically will do.

**Comment by SpiceyWolf** [comment]
how would that work when godot isnt normally an installed program?

**Comment by al1-ce** [comment]
Any godot executable is sufficient for dumping api and generating classes

**Comment by SpiceyWolf** [comment]
right but that wouldnt ve automatic unless u pointed at godot

**Comment by SpiceyWolf** [comment]
i only just realized im retarded cause all thats needed is to include a api file for it to gen from xD

**Comment by al1-ce** [comment]
I think we could whip up some small gui setup for that
Should make things easier

**Comment by al1-ce** [comment]
Actually depending on api file size it could be included in repo so that you still can auto-gen stuff for "latest" version and if you want you still would be able to gen api by hand

**Comment by SpiceyWolf** [comment]
the api file itself is about 5mb

**Comment by al1-ce** [comment]
Too much, gotta make put this burden on user

**Comment by Superbelko** [comment]
No need to know where is godot on local machine.
A simple wget/curl prebuild step should be enough, `godot-cpp` already has `extension_api.json` that we need so we can keep our repo nice and slim, and avoid unneeded redundancy. 

https://github.com/godotengine/godot-cpp/tree/master/gdextension

**Comment by SpiceyWolf** [comment]
lol u cray belko... gett'm!

**Comment by al1-ce** [comment]
That's convinient

**Comment by Superbelko** [comment]
@al1-ce do it, make v0.2.0 come true!

**Comment by al1-ce** [comment]
K, gonna do it today
